function translateToEmoji() {
    var textInput = document.getElementById("textInput").value;
    var emojiResult = document.getElementById("emojiResult");

   
    const emojiMap = {
        happy: "😊",
        sad: "😢",
        love: "❤️",
        cool: "😎",
        hello: "👋",
        grinning: "😀",
        grinningBigEyes: "😃",
        grinningSmilingEyes: "😄",
        beamingSmilingEyes: "😁",
        grinningSquinting: "😆",
        grinningSweat: "😅",
        rofl: "🤣",
        tearsOfJoy: "😂",
        slightlySmiling: "🙂",
        winking: "😉",
        smilingEyes: "😊",
        smilingHalo: "😇",
        smilingHearts: "🥰",
        heartEyes: "😍",
        starStruck: "🤩",
        blowingKiss: "😘",
        kissing: "😗",
        smilingFace: "☺️",
        kissingClosedEyes: "😚",
        kissingSmilingEyes: "😙",
        smilingTear: "🥲",
        smirking: "😏",
        savoringFood: "😋",
        tongueOut: "😛",
        winkingTongue: "😜",
        zany: "🤪",
        squintingTongue: "😝",
        moneyMouth: "🤑",
        openHands: "🤗",
        handOverMouth: "🤭",
        openEyesHandOverMouth: "🫢",
        peekingEye: "🫣",
        shushing: "🤫",
        thinking: "🤔",
        saluting: "🫡",
        drooling: "🤤",
        cowboy: "🤠",
        partying: "🥳",
        disguised: "🥸",
        sunglasses: "😎",
        nerd: "🤓",
        monocle: "🧐",
        upsideDown: "🙃",
        melting: "🫠",
        zipperMouth: "🤐",
        raisedEyebrow: "🤨",
        neutral: "😐",
        expressionless: "😑",
        withoutMouth: "😶",
        dottedLine: "🫥",
        faceInClouds: "😶‍🌫️",
        unamused: "😒",
        rollingEyes: "🙄",
        grimacing: "😬",
        exhaling: "😮‍💨",
        lying: "🤥",
        shaking: "🫨",
        headShakingHorizontal: "🙂‍↔️",
        headShakingVertical: "🙂‍↕️",
        relieved: "😌",
        pensive: "😔",
        sleepy: "😪",
        sleeping: "😴",
        bagsUnderEyes: "🫩",
        medicalMask: "😷",
        thermometer: "🤒",
        headBandage: "🤕",
        nauseated: "🤢",
        vomiting: "🤮",
        sneezing: "🤧",
        hotFace: "🥵",
        coldFace: "🥶",
        woozy: "🥴",
        crossedEyes: "😵",
        spiralEyes: "😵‍💫",
        explodingHead: "🤯",
        yawning: "🥱",
        confused: "😕",
        diagonalMouth: "🫤",
        worried: "😟",
        slightlyFrowning: "🙁",
        frowning: "☹️",
        openMouth: "😮",
        hushed: "😯",
        astonished: "😲",
        flushed: "😳",
        pleading: "🥺",
        holdingBackTears: "🥹",
        frowningOpenMouth: "😦",
        anguished: "😧",
        fearful: "😨",
        anxiousSweat: "😰",
        sadRelieved: "😥",
        crying: "😢",
        loudlyCrying: "😭",
        screamingFear: "😱",
        confounded: "😖",
        persevering: "😣",
        disappointed: "😞",
        downcastSweat: "😓",
        weary: "😩",
        tired: "😫",
        steamFromNose: "😤",
        enraged: "😡",
        angry: "😠",
        symbolsOnMouth: "🤬",
        angryHorns: "👿",
        smilingHorns: "😈",
        skull: "💀",
        skullCrossbones: "☠️",
        poo: "💩",
        clown: "🤡",
        ogre: "👹",
        goblin: "👺",
        ghost: "👻",
        alien: "👽",
        alienMonster: "👾",
        robot: "🤖",
        grinningCat: "😺",
        grinningCatSmilingEyes: "😸",
        catTearsOfJoy: "😹",
        catHeartEyes: "😻",
        catWrySmile: "😼",
        kissingCat: "😽",
        wearyCat: "🙀",
        cryingCat: "😿",
        poutingCat: "😾",
        seeNoEvil: "🙈",
        hearNoEvil: "🙉",
        speakNoEvil: "🙊"
    };
    

    // Replace words with corresponding emojis
    var translatedText = textInput
        .toLowerCase()
        .replace(/\b\w+\b/g, function (word) {
            return emojiMap[word] || word;
        });

    // Display the translated text with emojis
    emojiResult.textContent = translatedText;
}
